_wandb:
    value:
        cli_version: 0.21.4
        code_path: code/src/pipeline/wandb_datasets.ipynb
        e:
            a34dzt2zuu9c9s31ge0tfr33u1v3j30f:
                apple:
                    ecpuCores: 4
                    gpuCores: 40
                    memoryGb: 64
                    name: Apple M3 Max
                    pcpuCores: 12
                    ramTotalBytes: "68719476736"
                codePath: src/pipeline/wandb_datasets.ipynb
                codePathLocal: wandb_datasets.ipynb
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1995218165760"
                        used: "246084202496"
                email: jubacochran@gmail.com
                executable: /Users/jubacochran/projects/student/207/w207-predictive-maintenance/.venv/bin/python
                git:
                    commit: d89eab00eb9ccbd4562a82fcd48399f24567fd06
                    remote: https://github.com/PaulTerrasi/w207-predictive-maintenance.git
                host: Mac
                memory:
                    total: "68719476736"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/jubacochran/projects/student/207/w207-predictive-maintenance/src/pipeline/wandb_datasets.ipynb
                python: CPython 3.12.2
                root: /Users/jubacochran/projects/student/207/w207-predictive-maintenance/src/pipeline
                startedAt: "2025-09-16T17:37:07.687736Z"
                writerId: a34dzt2zuu9c9s31ge0tfr33u1v3j30f
        m: []
        python_version: 3.12.2
        t:
            "3":
                - 2
            "4": 3.12.2
            "5": 0.21.4
            "8":
                - 1
                - 2
            "12": 0.21.4
            "13": darwin-arm64
